test apt-get

diff --git a/bin/pre_compile b/bin/pre_compile
--- a/bin/pre_compile
+++ b/bin/pre_compile
@@ -3,4 +3,39 @@
 
 echo "=====> Inside pre_compile!!!"
 
-apt-get update && apt-get install -y libaio1
+# fail fast
+set -e
+
+LP_DIR=`cd $(dirname $0); cd ..; pwd`
+
+function error() {
+  echo " !     $*" >&2
+  exit 1
+}
+
+function topic() {
+  echo "-----> $*"
+}
+
+function indent() {
+  c='s/^/       /'
+  case $(uname) in
+    Darwin) sed -l "$c";;
+    *)      sed -u "$c";;
+  esac
+}
+
+APT_CACHE_DIR="$CACHE_DIR/apt/cache"
+APT_STATE_DIR="$CACHE_DIR/apt/state"
+
+mkdir -p "$APT_CACHE_DIR/archives/partial"
+mkdir -p "$APT_STATE_DIR/lists/partial"
+
+APT_OPTIONS="-o debug::nolocking=true -o dir::cache=$APT_CACHE_DIR -o dir::state=$APT_STATE_DIR"
+
+topic "Updating apt caches"
+apt-get $APT_OPTIONS update | indent
+
+topic "Fetching .debs for libaio1"
+apt-get $APT_OPTIONS -y --force-yes -d install --reinstall libaio1 | indent
+
