oracle jdk 1.8.0_131 install

diff --git a/bin/steps/java b/bin/steps/java
--- a/bin/steps/java
+++ b/bin/steps/java
@@ -1,51 +1,78 @@
 #!/usr/bin/env bash
 
 
-echo "=====> Prepare to download JDK"
+echo "=====> Inside pre_compile!!!"
 
 # fail fast
 set -e
 
-install_jdk_jdbc(){
+LP_DIR=`cd $(dirname $0); cd ..; pwd`
+
+function error() {
+  echo " !     $*" >&2
+  exit 1
+}
+
+function topic() {
+  echo "-----> $*"
+}
+
+function indent() {
+  c='s/^/       /'
+  case $(uname) in
+    Darwin) sed -l "$c";;
+    *)      sed -u "$c";;
+  esac
+}
+
+install_jdk(){
   echo $HOME
   echo $BUILD_DIR
-  
-  echo "_+_+_+_+_+_Downloading jdk"
+  #local build_dir=${1:-}
+  echo "Installing jdk"
   
   local java_home=$DEPS_DIR/$DEPS_IDX/java
   mkdir -p $java_home
-  
   cd $java_home
+  # local basic_download_url="http://files.cargosmart.org/python/instantclient-basic-linux.x64-11.2.0.4.0.tar.gz"
+  # local sdk_download_url="http://files.cargosmart.org/python/instantclient-sdk-linux.x64-11.2.0.4.0.tar.gz"
+
+  ####
+  #local basic_download_url="http://artifact:8081/artifactory/thirdparty_tools/thirdparty_lib/instantclient-basic-linux.x64-11.2.0.4.0/instantclient-basic-linux.x64-11.2.0.4.0/instantclient-basic-linux.x64-11.2.0.4.0-instantclient-basic-linux.x64-11.2.0.4.0.jar"
+  #local sdk_download_url="http://artifact:8081/artifactory/thirdparty_tools/thirdparty_lib/instantclient-sdk-linux.x64-11.2.0.4.0/instantclient-sdk-linux.x64-11.2.0.4.0/instantclient-sdk-linux.x64-11.2.0.4.0-instantclient-sdk-linux.x64-11.2.0.4.0.jar"
+
+  #curl -k "$basic_download_url" --silent --fail --retry 5 --retry-max-time 15 -o instantclient-basic.tar.gz
+  #echo "Downloaded [$basic_download_url]"
+  #curl -k "$sdk_download_url" --silent --fail --retry 5 --retry-max-time 15 -o instantclient-sdk.tar.gz
+  #echo "Downloaded [$sdk_download_url]"
+  ####
   
-  
-  local jdk_download_url="http://artifact:8081/artifactory/thirdparty_tools/thirdparty_lib/jdk-8u131-linux-x64/jdk-8u131-linux-x64/jdk-8u131-linux-x64-jdk-8u131-linux-x64.jar"
-  wget --no-proxy "$jdk_download_url"
-  echo "Downloaded [$jdk_download_url]"
-  
-  # Must store jar in artifactory... so need to rename back to tar.gz
-  echo "Rename to tar.gz"
-  mv jdk-8u131-linux-x64-jdk-8u131-linux-x64.jar jdk-8u131-linux-x64.tar.gz
-  
+  #local basic_download_url="http://ngsc-2-w7.corp.oocl.com:8080/jdk-8u172-linux-x64.tar.gz"
+  #curl -k "$basic_download_url" --silent --fail --retry 5 --retry-max-time 15 -o jdk-linux-x64.tar.gz
+  #echo "Downloaded [$basic_download_url]"
+  $BUILDPACK_PATH/compile-extensions/bin/download_dependency_by_name oraclejdk 1.8.0.131 jdk-linux-x64.tar.gz
+    
   echo "unzipping libraries"
-  tar -xvzf jdk-8u131-linux-x64.tar.gz
+  tar -xvzf jdk-linux-x64.tar.gz
   
-  rm jdk-8u131-linux-x64.tar.gz
+  rm jdk-linux-x64.tar.gz
   
-  append_profile_d JVM_HOME "\$DEPS_DIR/$DEPS_IDX/java/jdk1.8.0_131/jre/lib/amd64/server/libjvm.so"
-  echo $DEPS_DIR/$DEPS_IDX/java/jdk1.8.0_131/jre/lib/amd64/server/libjvm.so > $DEPS_DIR/$DEPS_IDX/env/JVM_HOME
+  mv jdk1.8.0_131 jdk
+  cd jdk
   
-  echo "_+_+_+_+_+_Downloading jdbc"
-  local jdbc_home=$DEPS_DIR/$DEPS_IDX/jdbc
-  mkdir -p $jdbc_home
-  
-  cd $jdbc_home
-  local jdbc_download_url="http://artifact:8081/artifactory/thirdparty_tools/thirdparty_lib/ojdbc6/6/ojdbc6-6.jar"
-  wget --no-proxy "$jdbc_download_url"
-  echo "Downloaded [$jdbc_download_url]"
-  
-  append_profile_d JDBC_HOME "\$DEPS_DIR/$DEPS_IDX/jdbc/ojdbc6-6.jar"
-  echo $DEPS_DIR/$DEPS_IDX/jdbc/ojdbc6-6.jar > $DEPS_DIR/$DEPS_IDX/env/JDBC_HOME
-  
+  # prepare env variables for "pip install" use during staging
+  # append_profile_d JAVA_HOME "\$DEPS_DIR/$DEPS_IDX/java/jdk"
+  echo $DEPS_DIR/$DEPS_IDX/java/jdk > $DEPS_DIR/$DEPS_IDX/env/JAVA_HOME
+    
+  # prepare env variables for python runtime use
+  # Shell scripts in .profile.d folder are triggered at the start of cf start app
+  mkdir -p $BUILD_DIR/.profile.d
+cat <<EOF >$BUILD_DIR/.profile.d/002_jdk.sh
+export JAVA_HOME="\$DEPS_DIR/$DEPS_IDX/java/jdk"
+export PATH="\$JAVA_HOME/bin:\$PATH"
+EOF
+  echo "Back to $BUILD_DIR.."
+  cd $BUILD_DIR 
 }
 
-install_jdk_jdbc
+install_jdk 
